name: GoruGoru-Server CI/CD (JAR)

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Rename JAR
        run: mv ./build/libs/*SNAPSHOT.jar ./gorugoru.jar

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: gorugoru.jar
          target: /home/ubuntu/gorugoru/tobe

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/gorugoru/current
            mkdir -p /home/ubuntu/gorugoru/current
            mv /home/ubuntu/gorugoru/tobe/gorugoru.jar /home/ubuntu/gorugoru/current/gorugoru.jar
            cd /home/ubuntu/gorugoru/current

            # 기존 프로세스 종료
            sudo fuser -k -n tcp 8080 || true

            # Spring Boot 실행 (Secrets 값 전부 따옴표 처리)
            nohup java -jar gorugoru.jar \
              --server.port=8080 \
              --spring.datasource.url="${{ secrets.DATABASE_URL }}" \
              --spring.datasource.username="${{ secrets.DATABASE_USERNAME }}" \
              --spring.datasource.password="${{ secrets.DATABASE_PASSWORD }}" \
              --jwt.secret="${{ secrets.JWT_SECRET }}" \
              --cloud.aws.s3.bucket="${{ secrets.AWS_BUCKET }}" \
              --cloud.aws.region.static="${{ secrets.AWS_REGION }}" \
              --openai.api.key="${{ secrets.OPENAI_API_KEY }}" \
              --clova.ocr.invoke-url="${{ secrets.CLOVA_OCR_INVOKE_URL }}" \
              --clova.ocr.secret-key="${{ secrets.CLOVA_OCR_SECRET }}" \
              --DESC_API_URL="${{ secrets.DESC_API_URL }}" \
              --TRANSLATE_API_URL="${{ secrets.TRANSLATE_API_URL }}" \
              --GOOGLE_MAP_API_KEY="${{ secrets.GOOGLE_MAP_API_KEY }}" \
              --ADD_STORE_API_URL="${{ secrets.ADD_STORE_API_URL }}" \
              --COURSE_RECOMMENDATION_API_URL="${{ secrets.COURSE_RECOMMENDATION_API_URL }}" \
              --CURRENCY_API_KEY="${{ secrets.CURRENCY_API_KEY }}" \
              > ./output.log 2>&1 &